version: '3'

services:
  web:
    restart: always
    image: fraunhoferiosb/frost-server:2.2
    environment:
      - serviceRootUrl=http://frost2.iotlab.com:8090/FROST-Server
      - plugins_multiDatastream_enable=true
      - plugins_plugins=de.securedimensions.frostserver.plugin.staplus.PluginPLUS
      - plugins_staplus_enable=true
      - plugins_staplus_enable_enforceOwnership=true
      - plugins_staplus_enable_enforceLicensing=true
      - plugins_staplus_enable_enforceObservationGroupLicensing=true
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
      - auth_provider=de.securedimensions.frostserver.auth.oauth2.OAuth2AuthProvider
      - auth_realmName=FROST-Server-STAplus
      - auth_allowAnonymousRead=false
      - auth_authenticateOnly=false
      - auth_role_read=read
      - auth_role_create=create
      - auth_role_update=update
      - auth_role_delete=delete
      - auth_role_admin=admin
      - auth_adminUid=f96e80d5-56bf-396f-a713-3f27f020bbe0
      - auth_oauth_introspectionUrl=https://www.authenix.eu/oauth/tokeninfo
      - auth_oauth_userinfoUrl=https://www.authenix.eu/openid/userinfo
      - auth_oauth_scope=idp
      - auth_oauth_clientId=53e6c7ee-09c0-4de4-87e9-bff9bd7c7c07
      - auth_oauth_clientSecret=01940b6a70403ced2e67eca018755988c112274588e841dd2632e8b5ce5ee9b2
      - auth_registerUserLocally=false
      - auth_userTable=USERS
      - auth_usernameColumn=USER_NAME
    ports:
      - 8090:8080
      - 1883:1883
    depends_on:
      - database

  database:
    restart: always
    image: postgis/postgis:14-3.2-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data
volumes:
    postgis_volume:
