version: '3'

services:
  web:
    restart: always
    image: fraunhoferiosb/frost-server:2.2
    environment:
      - serviceRootUrl=http://frost2.iotlab.com:8090/FROST-Server
      - plugins_multiDatastream_enable=true
      - plugins_plugins=de.securedimensions.frostserver.plugin.staplus.PluginPLUS
      - plugins_staplus_enable=true
      - plugins_staplus_enable_enforceOwnership=true
      - plugins_staplus_enable_enforceLicensing=true
      - plugins_staplus_enable_enforceObservationGroupLicensing=true
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
      - persistence_persistenceManagerImplementationClass=de.fraunhofer.iosb.ilt.sta.persistence.pgjooq.imp.PostgresPersistenceManager
      #- persistence_idGenerationMode=ServerAndClientGenerated
    ports:
      - 8090:8080
      - 1883:1883
    depends_on:
      - database

  database:
    restart: always
    image: postgis/postgis:14-3.2-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,uuid-ossp
    volumes:
      - postgis_volume:/var/lib/postgresql/data
volumes:
    postgis_volume:
