version: '3'

services:
  web:
    restart: always
    image: fraunhoferiosb/frost-server:2.2
    environment:
      #- serviceRootUrl=http://frost2.iotlab.com:8090/FROST-Server
      - serviceRootUrl=https://frost.iotlab.com/sensorthings2
      - plugins_multiDatastream_enable=true
      - plugins_plugins=de.securedimensions.frostserver.plugin.staplus.PluginPLUS
      - plugins_staplus_enable=true
      - plugins_staplus_enable_enforceOwnership=true
      - plugins_staplus_enable_enforceLicensing=true
      - plugins_staplus_enable_enforceObservationGroupLicensing=true
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
      - persistence_idGenerationMode=ServerGeneratedOnly
      - persistence_idGenerationMode_Party=ClientGeneratedOnly
      - auth_provider=de.securedimensions.frostserver.auth.oauth2.OAuth2AuthProvider
      - auth_realmName=FROST-Server-STAplus
      - auth_allowAnonymousRead=true
      - auth_authenticateOnly=true
      - auth_role_read=read
      - auth_role_create=create
      - auth_role_update=update
      - auth_role_delete=delete
      - auth_role_admin=admin
      - auth_adminUid=XXX
      - auth_oauth_introspectionUrl=https://www.authenix.eu/oauth/tokeninfo
      - auth_oauth_userinfoUrl=https://www.authenix.eu/openid/userinfo
      - auth_oauth_scope=idp
      - auth_oauth_clientId=XXX
      - auth_oauth_clientSecret=XXX
      - auth_registerUserLocally=false
      - auth_userTable=USERS
      - auth_usernameColumn=USER_NAME
    ports:
      - 8090:8080
      - 1883:1883
    depends_on:
      - database

  database:
    restart: always
    image: postgis/postgis:14-3.2-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data
volumes:
    postgis_volume:
